sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CUuQj7nzL94T2/BAK2JC+H3ee9NgHH8z6EdAxzfg94oY3pa9mnRSfRwHlQUMkbXXdgT2tfXxkQKsTzlHcJq4Oe7Bs+yk3SulNUMdem3pCPmJCF/XMdvm5DqTxJstIt9o9iyVEfW4yOUpoxWadUok6WpE+JwqaaigRcs7Ej63th4MMyl+ctRNVQBhKec/WAOTEf7IOxk5KzQOYMvA+JTutml8FW5UQv+mZgGwTHNbVsMc87ibQ/cjw2Z6kY6b98ThKEuAmyOqW26PRDctsjIxKkcBC1rVVqFDphj6GpHlv/DZjD7c+ShTBhWIr9YxPQA3UZ6t2S9hcnI6c3kwMV81CT8wSEKN/HOO7fOBS3J77fV29ReVtE2npfmaNm7LmcgcQya16iBGOSa+S9PqjCKhsL9YiOJq6UfNjn3rDra2Wyh8i3mwfwGBl2Rvho2Svi0Qjk/Vbm4LMGvGoXeXlZl6DJHnsP5THubeT+ydx/QoHL9JwcCBsK+Ovjh30xi0CVd6oIWEueffBeaHW9sCnt+N9RnVWRLaonaC8XcmPrJ8h2u2/6Aabuh81pCwVB/iQm/1qc67qmBcOmvcjFjV1oCQisVo2QzH8U2IoIN3Ry2P1GIT/1t+NaqpWNFDKsqq5JwGfY2IO4rZKVQkcRa7Rj4oRs9cCi5SIog+3AK0QKq++Kk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Novelle_2320
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy